// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    user_id, action, entity, entity_id, "before", "after", ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, action, entity, entity_id, details, ip_address, created_at, before, after
`

type CreateAuditLogParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Action    string      `json:"action"`
	Entity    pgtype.Text `json:"entity"`
	EntityID  pgtype.UUID `json:"entity_id"`
	Before    []byte      `json:"before"`
	After     []byte      `json:"after"`
	IpAddress pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.UserID,
		arg.Action,
		arg.Entity,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.IpAddress,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Entity,
		&i.EntityID,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
		&i.Before,
		&i.After,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, user_id, action, entity, entity_id, details, ip_address, created_at, before, after FROM audit_logs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Entity,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.Before,
			&i.After,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
