// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package repository

import (
	"context"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    key, response_status, response_body
) VALUES (
    $1, $2, $3
) RETURNING key, response_status, response_body, created_at
`

type CreateIdempotencyKeyParams struct {
	Key            string `json:"key"`
	ResponseStatus int32  `json:"response_status"`
	ResponseBody   []byte `json:"response_body"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey, arg.Key, arg.ResponseStatus, arg.ResponseBody)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, response_status, response_body, created_at FROM idempotency_keys
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}
