// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	Entity    pgtype.Text        `json:"entity"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Details   []byte             `json:"details"`
	IpAddress pgtype.Text        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Before    []byte             `json:"before"`
	After     []byte             `json:"after"`
}

type AuthUser struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	EncryptedPassword string             `json:"encrypted_password"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	Key            string             `json:"key"`
	ResponseStatus int32              `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Order struct {
	ID             pgtype.UUID        `json:"id"`
	StoreID        pgtype.UUID        `json:"store_id"`
	TableSessionID pgtype.UUID        `json:"table_session_id"`
	CashierID      pgtype.UUID        `json:"cashier_id"`
	OrderNumber    string             `json:"order_number"`
	Status         string             `json:"status"`
	PaymentStatus  string             `json:"payment_status"`
	TotalAmount    pgtype.Numeric     `json:"total_amount"`
	TaxAmount      pgtype.Numeric     `json:"tax_amount"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	FinalAmount    pgtype.Numeric     `json:"final_amount"`
	Note           pgtype.Text        `json:"note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID           pgtype.UUID    `json:"id"`
	OrderID      pgtype.UUID    `json:"order_id"`
	ProductID    pgtype.UUID    `json:"product_id"`
	ProductName  string         `json:"product_name"`
	ProductPrice pgtype.Numeric `json:"product_price"`
	Quantity     int32          `json:"quantity"`
	TotalPrice   pgtype.Numeric `json:"total_price"`
	Note         pgtype.Text    `json:"note"`
}

type Payment struct {
	ID              pgtype.UUID        `json:"id"`
	OrderID         pgtype.UUID        `json:"order_id"`
	PaymentMethod   string             `json:"payment_method"`
	Amount          pgtype.Numeric     `json:"amount"`
	ReferenceNumber pgtype.Text        `json:"reference_number"`
	Status          string             `json:"status"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	QrisUrl         pgtype.Text        `json:"qris_url"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Price       pgtype.Numeric     `json:"price"`
	Stock       int32              `json:"stock"`
	Category    pgtype.Text        `json:"category"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	StoreID     pgtype.UUID        `json:"store_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	IsAvailable pgtype.Bool        `json:"is_available"`
	Description pgtype.Text        `json:"description"`
	Sku         pgtype.Text        `json:"sku"`
}

type Profile struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FullName     pgtype.Text        `json:"full_name"`
	StoreID      pgtype.UUID        `json:"store_id"`
	Email        pgtype.Text        `json:"email"`
}

type Role struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Shift struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	StoreID      pgtype.UUID        `json:"store_id"`
	OpenedAt     pgtype.Timestamptz `json:"opened_at"`
	ClosedAt     pgtype.Timestamptz `json:"closed_at"`
	OpeningCash  pgtype.Numeric     `json:"opening_cash"`
	ClosingCash  pgtype.Numeric     `json:"closing_cash"`
	ExpectedCash pgtype.Numeric     `json:"expected_cash"`
}

type StockMovement struct {
	ID          pgtype.UUID        `json:"id"`
	ProductID   pgtype.UUID        `json:"product_id"`
	Quantity    int32              `json:"quantity"`
	Type        string             `json:"type"`
	ReferenceID pgtype.UUID        `json:"reference_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Store struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Address   pgtype.Text        `json:"address"`
	Phone     pgtype.Text        `json:"phone"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Table struct {
	ID        pgtype.UUID        `json:"id"`
	StoreID   pgtype.UUID        `json:"store_id"`
	Name      string             `json:"name"`
	Capacity  pgtype.Int4        `json:"capacity"`
	QrCode    pgtype.Text        `json:"qr_code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TableSession struct {
	ID        pgtype.UUID        `json:"id"`
	TableID   pgtype.UUID        `json:"table_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserRole struct {
	UserID     pgtype.UUID        `json:"user_id"`
	RoleCode   string             `json:"role_code"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
}
