// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    store_id, table_session_id, cashier_id, order_number, 
    total_amount, tax_amount, discount_amount, final_amount, note, status, payment_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, store_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at
`

type CreateOrderParams struct {
	StoreID        pgtype.UUID    `json:"store_id"`
	TableSessionID pgtype.UUID    `json:"table_session_id"`
	CashierID      pgtype.UUID    `json:"cashier_id"`
	OrderNumber    string         `json:"order_number"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	FinalAmount    pgtype.Numeric `json:"final_amount"`
	Note           pgtype.Text    `json:"note"`
	Status         string         `json:"status"`
	PaymentStatus  string         `json:"payment_status"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.StoreID,
		arg.TableSessionID,
		arg.CashierID,
		arg.OrderNumber,
		arg.TotalAmount,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.FinalAmount,
		arg.Note,
		arg.Status,
		arg.PaymentStatus,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableSessionID,
		&i.CashierID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, product_name, product_price, quantity, total_price, note
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, order_id, product_id, product_name, product_price, quantity, total_price, note
`

type CreateOrderItemParams struct {
	OrderID      pgtype.UUID    `json:"order_id"`
	ProductID    pgtype.UUID    `json:"product_id"`
	ProductName  string         `json:"product_name"`
	ProductPrice pgtype.Numeric `json:"product_price"`
	Quantity     int32          `json:"quantity"`
	TotalPrice   pgtype.Numeric `json:"total_price"`
	Note         pgtype.Text    `json:"note"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.ProductPrice,
		arg.Quantity,
		arg.TotalPrice,
		arg.Note,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.ProductPrice,
		&i.Quantity,
		&i.TotalPrice,
		&i.Note,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, store_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableSessionID,
		&i.CashierID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersBySession = `-- name: GetOrdersBySession :many
SELECT id, store_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at FROM orders
WHERE table_session_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetOrdersBySession(ctx context.Context, tableSessionID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersBySession, tableSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.TableSessionID,
			&i.CashierID,
			&i.OrderNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.TotalAmount,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.FinalAmount,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByStore = `-- name: ListOrdersByStore :many
SELECT id, store_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at FROM orders
WHERE store_id = $1 
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByStoreParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListOrdersByStore(ctx context.Context, arg ListOrdersByStoreParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByStore, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.TableSessionID,
			&i.CashierID,
			&i.OrderNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.TotalAmount,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.FinalAmount,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :one
UPDATE orders
SET payment_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, store_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at
`

type UpdateOrderPaymentStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	PaymentStatus string      `json:"payment_status"`
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderPaymentStatus, arg.ID, arg.PaymentStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableSessionID,
		&i.CashierID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, store_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.TableSessionID,
		&i.CashierID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
