// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    outlet_id, table_session_id, cashier_id, order_number, 
    total_amount, tax_amount, discount_amount, final_amount, note
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, outlet_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at
`

type CreateOrderParams struct {
	OutletID       pgtype.UUID    `json:"outlet_id"`
	TableSessionID pgtype.UUID    `json:"table_session_id"`
	CashierID      pgtype.UUID    `json:"cashier_id"`
	OrderNumber    string         `json:"order_number"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	FinalAmount    pgtype.Numeric `json:"final_amount"`
	Note           pgtype.Text    `json:"note"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.OutletID,
		arg.TableSessionID,
		arg.CashierID,
		arg.OrderNumber,
		arg.TotalAmount,
		arg.TaxAmount,
		arg.DiscountAmount,
		arg.FinalAmount,
		arg.Note,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.TableSessionID,
		&i.CashierID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, product_name, product_price, quantity, total_price, note
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, order_id, product_id, product_name, product_price, quantity, total_price, note
`

type CreateOrderItemParams struct {
	OrderID      pgtype.UUID    `json:"order_id"`
	ProductID    pgtype.UUID    `json:"product_id"`
	ProductName  string         `json:"product_name"`
	ProductPrice pgtype.Numeric `json:"product_price"`
	Quantity     int32          `json:"quantity"`
	TotalPrice   pgtype.Numeric `json:"total_price"`
	Note         pgtype.Text    `json:"note"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.ProductPrice,
		arg.Quantity,
		arg.TotalPrice,
		arg.Note,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.ProductPrice,
		&i.Quantity,
		&i.TotalPrice,
		&i.Note,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, outlet_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.TableSessionID,
		&i.CashierID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByOutlet = `-- name: ListOrdersByOutlet :many
SELECT id, outlet_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at FROM orders
WHERE outlet_id = $1 
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByOutletParams struct {
	OutletID pgtype.UUID `json:"outlet_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListOrdersByOutlet(ctx context.Context, arg ListOrdersByOutletParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByOutlet, arg.OutletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.TableSessionID,
			&i.CashierID,
			&i.OrderNumber,
			&i.Status,
			&i.PaymentStatus,
			&i.TotalAmount,
			&i.TaxAmount,
			&i.DiscountAmount,
			&i.FinalAmount,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :one
UPDATE orders
SET payment_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, outlet_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at
`

type UpdateOrderPaymentStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	PaymentStatus string      `json:"payment_status"`
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderPaymentStatus, arg.ID, arg.PaymentStatus)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.TableSessionID,
		&i.CashierID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, outlet_id, table_session_id, cashier_id, order_number, status, payment_status, total_amount, tax_amount, discount_amount, final_amount, note, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.TableSessionID,
		&i.CashierID,
		&i.OrderNumber,
		&i.Status,
		&i.PaymentStatus,
		&i.TotalAmount,
		&i.TaxAmount,
		&i.DiscountAmount,
		&i.FinalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
