// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outlets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutlet = `-- name: CreateOutlet :one
INSERT INTO outlets (name, address, phone)
VALUES ($1, $2, $3)
RETURNING id, name, address, phone, created_at, updated_at
`

type CreateOutletParams struct {
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
}

func (q *Queries) CreateOutlet(ctx context.Context, arg CreateOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, createOutlet, arg.Name, arg.Address, arg.Phone)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOutlet = `-- name: DeleteOutlet :exec
DELETE FROM outlets
WHERE id = $1
`

func (q *Queries) DeleteOutlet(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOutlet, id)
	return err
}

const getOutlet = `-- name: GetOutlet :one
SELECT id, name, address, phone, created_at, updated_at FROM outlets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOutlet(ctx context.Context, id pgtype.UUID) (Outlet, error) {
	row := q.db.QueryRow(ctx, getOutlet, id)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOutlets = `-- name: ListOutlets :many
SELECT id, name, address, phone, created_at, updated_at FROM outlets
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListOutletsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOutlets(ctx context.Context, arg ListOutletsParams) ([]Outlet, error) {
	rows, err := q.db.Query(ctx, listOutlets, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Outlet
	for rows.Next() {
		var i Outlet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOutlet = `-- name: UpdateOutlet :one
UPDATE outlets
SET name = $2, address = $3, phone = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, address, phone, created_at, updated_at
`

type UpdateOutletParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateOutlet(ctx context.Context, arg UpdateOutletParams) (Outlet, error) {
	row := q.db.QueryRow(ctx, updateOutlet,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
	)
	var i Outlet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
