// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    order_id, payment_method, amount, status, qris_url
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, order_id, payment_method, amount, reference_number, status, paid_at, created_at, qris_url
`

type CreatePaymentParams struct {
	OrderID       pgtype.UUID    `json:"order_id"`
	PaymentMethod string         `json:"payment_method"`
	Amount        pgtype.Numeric `json:"amount"`
	Status        string         `json:"status"`
	QrisUrl       pgtype.Text    `json:"qris_url"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.PaymentMethod,
		arg.Amount,
		arg.Status,
		arg.QrisUrl,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethod,
		&i.Amount,
		&i.ReferenceNumber,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.QrisUrl,
	)
	return i, err
}

const getPaymentByOrder = `-- name: GetPaymentByOrder :one
SELECT id, order_id, payment_method, amount, reference_number, status, paid_at, created_at, qris_url FROM payments
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByOrder(ctx context.Context, orderID pgtype.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrder, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethod,
		&i.Amount,
		&i.ReferenceNumber,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.QrisUrl,
	)
	return i, err
}

const updatePaymentQRIS = `-- name: UpdatePaymentQRIS :exec
UPDATE payments
SET qris_url = $2
WHERE id = $1
`

type UpdatePaymentQRISParams struct {
	ID      pgtype.UUID `json:"id"`
	QrisUrl pgtype.Text `json:"qris_url"`
}

func (q *Queries) UpdatePaymentQRIS(ctx context.Context, arg UpdatePaymentQRISParams) error {
	_, err := q.db.Exec(ctx, updatePaymentQRIS, arg.ID, arg.QrisUrl)
	return err
}
