// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    store_id, category_id, name, description, sku, price, stock, image_url, is_available
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, price, stock, category, created_at, updated_at, store_id, category_id, image_url, is_available, description, sku
`

type CreateProductParams struct {
	StoreID     pgtype.UUID    `json:"store_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Sku         pgtype.Text    `json:"sku"`
	Price       pgtype.Numeric `json:"price"`
	Stock       int32          `json:"stock"`
	ImageUrl    pgtype.Text    `json:"image_url"`
	IsAvailable pgtype.Bool    `json:"is_available"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.StoreID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.Sku,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
		arg.IsAvailable,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreID,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsAvailable,
		&i.Description,
		&i.Sku,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, price, stock, category, created_at, updated_at, store_id, category_id, image_url, is_available, description, sku FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreID,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsAvailable,
		&i.Description,
		&i.Sku,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price, stock, category, created_at, updated_at, store_id, category_id, image_url, is_available, description, sku FROM products
WHERE store_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoreID,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsAvailable,
			&i.Description,
			&i.Sku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock = stock + $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, price, stock, category, created_at, updated_at, store_id, category_id, image_url, is_available, description, sku
`

type UpdateProductStockParams struct {
	ID    pgtype.UUID `json:"id"`
	Stock int32       `json:"stock"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.Stock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreID,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsAvailable,
		&i.Description,
		&i.Sku,
	)
	return i, err
}
