// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (outlet_id, name)
VALUES ($1, $2)
RETURNING id, outlet_id, name, created_at
`

type CreateCategoryParams struct {
	OutletID pgtype.UUID `json:"outlet_id"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.OutletID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OutletID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    outlet_id, category_id, name, price, stock, image_url, is_available
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, price, stock, category, created_at, updated_at, outlet_id, category_id, image_url, is_available
`

type CreateProductParams struct {
	OutletID    pgtype.UUID    `json:"outlet_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Name        string         `json:"name"`
	Price       pgtype.Numeric `json:"price"`
	Stock       int32          `json:"stock"`
	ImageUrl    pgtype.Text    `json:"image_url"`
	IsAvailable pgtype.Bool    `json:"is_available"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.OutletID,
		arg.CategoryID,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.ImageUrl,
		arg.IsAvailable,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutletID,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsAvailable,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, price, stock, category, created_at, updated_at, outlet_id, category_id, image_url, is_available FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OutletID,
		&i.CategoryID,
		&i.ImageUrl,
		&i.IsAvailable,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, outlet_id, name, created_at FROM categories
WHERE outlet_id = $1
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context, outletID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, outletID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.OutletID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price, stock, category, created_at, updated_at, outlet_id, category_id, image_url, is_available FROM products
WHERE outlet_id = $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	OutletID pgtype.UUID `json:"outlet_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.OutletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OutletID,
			&i.CategoryID,
			&i.ImageUrl,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE products
SET stock = stock + $2, updated_at = NOW()
WHERE id = $1
`

type UpdateProductStockParams struct {
	ID    pgtype.UUID `json:"id"`
	Stock int32       `json:"stock"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.Exec(ctx, updateProductStock, arg.ID, arg.Stock)
	return err
}
