// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (
    id, email, full_name, role, store_id
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, username, password_hash, role, created_at, full_name, store_id, email
`

type CreateProfileParams struct {
	ID       pgtype.UUID `json:"id"`
	Email    pgtype.Text `json:"email"`
	FullName pgtype.Text `json:"full_name"`
	Role     string      `json:"role"`
	StoreID  pgtype.UUID `json:"store_id"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.StoreID,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.FullName,
		&i.StoreID,
		&i.Email,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, username, password_hash, role, created_at, full_name, store_id, email FROM profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.FullName,
		&i.StoreID,
		&i.Email,
	)
	return i, err
}

const getProfileByEmail = `-- name: GetProfileByEmail :one
SELECT id, username, password_hash, role, created_at, full_name, store_id, email FROM profiles
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetProfileByEmail(ctx context.Context, email pgtype.Text) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByEmail, email)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.FullName,
		&i.StoreID,
		&i.Email,
	)
	return i, err
}
