// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CloseShift(ctx context.Context, arg CloseShiftParams) (Shift, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOutlet(ctx context.Context, arg CreateOutletParams) (Outlet, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (TableSession, error)
	CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (Table, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteOutlet(ctx context.Context, id pgtype.UUID) error
	GetCurrentShift(ctx context.Context, userID pgtype.UUID) (Shift, error)
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	GetOrder(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrdersBySession(ctx context.Context, tableSessionID pgtype.UUID) ([]Order, error)
	GetOutlet(ctx context.Context, id pgtype.UUID) (Outlet, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	GetRole(ctx context.Context, code string) (Role, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetShiftById(ctx context.Context, id pgtype.UUID) (Shift, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]GetUserRolesRow, error)
	InvalidateSession(ctx context.Context, id pgtype.UUID) error
	ListCategories(ctx context.Context, outletID pgtype.UUID) ([]Category, error)
	ListOrdersByOutlet(ctx context.Context, arg ListOrdersByOutletParams) ([]Order, error)
	ListOutlets(ctx context.Context, arg ListOutletsParams) ([]Outlet, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error)
	ListTables(ctx context.Context, outletID pgtype.UUID) ([]Table, error)
	UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateOutlet(ctx context.Context, arg UpdateOutletParams) (Outlet, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
}

var _ Querier = (*Queries)(nil)
