// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CloseShift(ctx context.Context, arg CloseShiftParams) (Shift, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) (AuthUser, error)
	CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (TableSession, error)
	CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	DeleteStore(ctx context.Context, id pgtype.UUID) error
	GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error)
	GetCurrentShift(ctx context.Context, userID pgtype.UUID) (Shift, error)
	GetIdempotencyKey(ctx context.Context, key string) (IdempotencyKey, error)
	GetOrder(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrdersBySession(ctx context.Context, tableSessionID pgtype.UUID) ([]Order, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProfile(ctx context.Context, id pgtype.UUID) (Profile, error)
	GetProfileByEmail(ctx context.Context, email pgtype.Text) (Profile, error)
	GetRole(ctx context.Context, code string) (Role, error)
	GetSessionByToken(ctx context.Context, token string) (TableSession, error)
	GetStore(ctx context.Context, id pgtype.UUID) (Store, error)
	GetTableSessions(ctx context.Context, storeID pgtype.UUID) ([]GetTableSessionsRow, error)
	GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]GetUserRolesRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListOrdersByStore(ctx context.Context, arg ListOrdersByStoreParams) ([]Order, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error)
	ListStores(ctx context.Context, arg ListStoresParams) ([]Store, error)
	UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
}

var _ Querier = (*Queries)(nil)
