// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_code)
VALUES ($1, $2)
`

type AssignRoleToUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	RoleCode string      `json:"role_code"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleCode)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (code, name, description)
VALUES ($1, $2, $3)
RETURNING code, name, description
`

type CreateRoleParams struct {
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Code, arg.Name, arg.Description)
	var i Role
	err := row.Scan(&i.Code, &i.Name, &i.Description)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT code, name, description FROM roles
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetRole(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, code)
	var i Role
	err := row.Scan(&i.Code, &i.Name, &i.Description)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.code, r.name 
FROM roles r
JOIN user_roles ur ON r.code = ur.role_code
WHERE ur.user_id = $1
`

type GetUserRolesRow struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]GetUserRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRolesRow
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT code, name, description FROM roles
ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.Code, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
