// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO table_sessions (
    table_id, token, expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, table_id, token, expires_at, is_active, created_at
`

type CreateSessionParams struct {
	TableID   pgtype.UUID        `json:"table_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (TableSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.TableID, arg.Token, arg.ExpiresAt)
	var i TableSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Token,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, table_id, token, expires_at, is_active, created_at FROM table_sessions
WHERE token = $1 LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (TableSession, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i TableSession
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Token,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTableSessions = `-- name: GetTableSessions :many
SELECT ts.id, ts.table_id, ts.token, ts.expires_at, ts.is_active, ts.created_at, t.store_id, t.name as table_name 
FROM table_sessions ts
JOIN tables t ON ts.table_id = t.id
WHERE t.store_id = $1
ORDER BY ts.created_at DESC
`

type GetTableSessionsRow struct {
	ID        pgtype.UUID        `json:"id"`
	TableID   pgtype.UUID        `json:"table_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	StoreID   pgtype.UUID        `json:"store_id"`
	TableName string             `json:"table_name"`
}

func (q *Queries) GetTableSessions(ctx context.Context, storeID pgtype.UUID) ([]GetTableSessionsRow, error) {
	rows, err := q.db.Query(ctx, getTableSessions, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTableSessionsRow
	for rows.Next() {
		var i GetTableSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.Token,
			&i.ExpiresAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.StoreID,
			&i.TableName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
