// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shifts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeShift = `-- name: CloseShift :one
UPDATE shifts
SET end_time = NOW(),
    end_cash = $2,
    expected_cash = $3
WHERE id = $1
RETURNING id, user_id, outlet_id, start_time, end_time, start_cash, end_cash, expected_cash
`

type CloseShiftParams struct {
	ID           pgtype.UUID    `json:"id"`
	EndCash      pgtype.Numeric `json:"end_cash"`
	ExpectedCash pgtype.Numeric `json:"expected_cash"`
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, closeShift, arg.ID, arg.EndCash, arg.ExpectedCash)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OutletID,
		&i.StartTime,
		&i.EndTime,
		&i.StartCash,
		&i.EndCash,
		&i.ExpectedCash,
	)
	return i, err
}

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (
    user_id, outlet_id, start_cash
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, outlet_id, start_time, end_time, start_cash, end_cash, expected_cash
`

type CreateShiftParams struct {
	UserID    pgtype.UUID    `json:"user_id"`
	OutletID  pgtype.UUID    `json:"outlet_id"`
	StartCash pgtype.Numeric `json:"start_cash"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, createShift, arg.UserID, arg.OutletID, arg.StartCash)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OutletID,
		&i.StartTime,
		&i.EndTime,
		&i.StartCash,
		&i.EndCash,
		&i.ExpectedCash,
	)
	return i, err
}

const getCurrentShift = `-- name: GetCurrentShift :one
SELECT id, user_id, outlet_id, start_time, end_time, start_cash, end_cash, expected_cash FROM shifts
WHERE user_id = $1 AND end_time IS NULL
LIMIT 1
`

func (q *Queries) GetCurrentShift(ctx context.Context, userID pgtype.UUID) (Shift, error) {
	row := q.db.QueryRow(ctx, getCurrentShift, userID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OutletID,
		&i.StartTime,
		&i.EndTime,
		&i.StartCash,
		&i.EndCash,
		&i.ExpectedCash,
	)
	return i, err
}

const getShiftById = `-- name: GetShiftById :one
SELECT id, user_id, outlet_id, start_time, end_time, start_cash, end_cash, expected_cash FROM shifts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetShiftById(ctx context.Context, id pgtype.UUID) (Shift, error) {
	row := q.db.QueryRow(ctx, getShiftById, id)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OutletID,
		&i.StartTime,
		&i.EndTime,
		&i.StartCash,
		&i.EndCash,
		&i.ExpectedCash,
	)
	return i, err
}

const listShifts = `-- name: ListShifts :many
SELECT id, user_id, outlet_id, start_time, end_time, start_cash, end_cash, expected_cash FROM shifts
WHERE outlet_id = $1
ORDER BY start_time DESC
LIMIT $2 OFFSET $3
`

type ListShiftsParams struct {
	OutletID pgtype.UUID `json:"outlet_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error) {
	rows, err := q.db.Query(ctx, listShifts, arg.OutletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shift
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OutletID,
			&i.StartTime,
			&i.EndTime,
			&i.StartCash,
			&i.EndCash,
			&i.ExpectedCash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
