// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shifts.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeShift = `-- name: CloseShift :one
UPDATE shifts
SET closed_at = NOW(),
    closing_cash = $2,
    expected_cash = $3
WHERE id = $1
RETURNING id, user_id, store_id, opened_at, closed_at, opening_cash, closing_cash, expected_cash
`

type CloseShiftParams struct {
	ID           pgtype.UUID    `json:"id"`
	ClosingCash  pgtype.Numeric `json:"closing_cash"`
	ExpectedCash pgtype.Numeric `json:"expected_cash"`
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, closeShift, arg.ID, arg.ClosingCash, arg.ExpectedCash)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.OpeningCash,
		&i.ClosingCash,
		&i.ExpectedCash,
	)
	return i, err
}

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (
    user_id, store_id, opening_cash
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, store_id, opened_at, closed_at, opening_cash, closing_cash, expected_cash
`

type CreateShiftParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	StoreID     pgtype.UUID    `json:"store_id"`
	OpeningCash pgtype.Numeric `json:"opening_cash"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, createShift, arg.UserID, arg.StoreID, arg.OpeningCash)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.OpeningCash,
		&i.ClosingCash,
		&i.ExpectedCash,
	)
	return i, err
}

const getCurrentShift = `-- name: GetCurrentShift :one
SELECT id, user_id, store_id, opened_at, closed_at, opening_cash, closing_cash, expected_cash FROM shifts
WHERE user_id = $1 AND closed_at IS NULL
LIMIT 1
`

func (q *Queries) GetCurrentShift(ctx context.Context, userID pgtype.UUID) (Shift, error) {
	row := q.db.QueryRow(ctx, getCurrentShift, userID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.OpeningCash,
		&i.ClosingCash,
		&i.ExpectedCash,
	)
	return i, err
}

const listShifts = `-- name: ListShifts :many
SELECT id, user_id, store_id, opened_at, closed_at, opening_cash, closing_cash, expected_cash FROM shifts
WHERE store_id = $1
ORDER BY opened_at DESC
LIMIT $2 OFFSET $3
`

type ListShiftsParams struct {
	StoreID pgtype.UUID `json:"store_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error) {
	rows, err := q.db.Query(ctx, listShifts, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shift
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreID,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.OpeningCash,
			&i.ClosingCash,
			&i.ExpectedCash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
